CREATE TABLE public.role
(
    role_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    role_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (role_id),
    CONSTRAINT uk_epk9im9l9q67xmwi4hbed25do UNIQUE (role_name)
)

TABLESPACE pg_default;

ALTER TABLE public.role
    OWNER to postgres;